_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.5
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 32
classes:
    value:
        - airplane
        - helicopter
        - train
        - street_music
        - engine
        - siren
        - car_horn
epochs:
    value: 500
learning_rate:
    value: 0.001
num_samples:
    value: 80000
sample_rate:
    value: 16000
